CC = gcc
CFLAGS = -Wall -Wextra -std=c11 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L

COMMON = dijks.c siim.c
GUI = Main.c drawing.c animation.c

milestone1:
	$(CC) $(CFLAGS) -o dijkstra dijks.c siim.c -lm

milestone2:
	$(CC) $(CFLAGS) -o sim $(COMMON) Main.c drawing.c -lraylib -lm -lX11 -lpthread -ldl -lrt

milestone3:
	$(CC) $(CFLAGS) -o sim $(COMMON) $(GUI) -lraylib -lm -lX11 -lpthread -ldl -lrt

milestone4:
	$(CC) $(CFLAGS) -o sim $(COMMON) $(GUI) -lraylib -lm -lX11 -lpthread -ldl -lrt

milestone5:
	$(CC) $(CFLAGS) -o sim $(COMMON) $(GUI) -lraylib -lm -lX11 -lpthread -ldl -lrt

clean:
	rm -f dijkstra sim *.o